### PR TITLE
fix: require admin auth for upload endpoint and fail closed on missin…

### LINKED ISSUE #809: Security: Unauthenticated catalog upload allows data poisoning
### Description
In `backend/main.py` (lines 932-1006), the upload endpoint relies solely on CSRF protection but lacks an authentication or authorization gate. Furthermore, it falls back to an anonymous Supabase client when admin credentials are missing. 

### Impact
**Data Poisoning:** Any caller who can obtain a CSRF token can import arbitrary CSV/JSON data into the products catalog. An attacker can inject junk rows at scale, poisoning the recommendation catalog and forcing downstream models to train on attacker-controlled data.

### Suggested Fix
Implement a strict admin authorization dependency (e.g., a required JWT or Admin Session) on the route before processing the upload, and explicitly fail if admin Supabase credentials are not configured.

### PR DESCRIPTION
**Pull request by sanrishi**
### 🛠️ Description of Changes
Secured the `/api/upload` and `/api/build` endpoints against unauthenticated access and data poisoning (Issue #809). Previously, these routes lacked proper admin authorization and dangerously fell back to an anonymous database client if admin credentials were misconfigured, effectively making catalog writes public. 

Additionally, this PR cleans up several syntax and compilation errors introduced by previous bad merges.

**Key Improvements:**
- **Strict Authorization:** Added `admin=Depends(_require_admin_access)` to the `/api/upload` endpoint, ensuring only authenticated administrators can inject data into the recommendation catalog.
- **Fail-Closed DB Clients:** Removed the anonymous Supabase client fallback in both `/api/upload` and `/api/build`. The system now correctly fails closed (raising a 500 `RuntimeError`) if `get_supabase_admin()` returns `None`.
- **Merge Artifact Cleanup:** Fixed a malformed function signature on `/api/upload` (removed a stray `import math` and improperly placed CSRF dependency).
- **Syntax & Strictness Fixes:** Resolved an orphaned `except (RedisError, TypeError)` block and corrected global variable declarations to comply with Python 3.14 strict scoping rules.

### 🧪 How Has This Been Tested?
- [x] Verified that `/api/upload` requests without a valid admin session are rejected with a 401/403 status code.
- [x] Confirmed that removing admin credentials from the environment causes `/api/upload` and `/api/build` to fail securely (HTTP 500) rather than falling back to anonymous access.
- [x] Verified that the application compiles cleanly without syntax or scoping errors under Python 3.14.
- [x] Passed all security and authorization regression suites.

### 📸 Proof & Visuals
*N/A - Security hardening and syntax compilation fixes.*

### ✔️ Checklist
- [x] My code follows the style guidelines of this project
- [x] My changes generate no new warnings

Fixes #809

### CODE REVIEW

**Review by leonagoel — APPROVED** [review]

**Comment by leonagoel** [comment]
🎉 **Merged!**

Points will reflect on the GSSoC leaderboard at next **4 AM IST** refresh.

🏆 https://gssoc.girlscript.org/leaderboard
